log_group_name: "/aws/application-signals/data"
namespace: "ApplicationSignals"
middleware: agenthealth/logs
dimension_rollup_option: "NoDimensionRollup"
metric_declarations:
  - dimensions:
      - [Environment, Service, Operation]
      - [Environment, Service]
    label_matchers:
      - label_names:
          - aws.span.kind
        regex: '^(SERVER|LOCAL_ROOT)$'
    metric_name_selectors:
      - Latency
      - Fault
      - Error
  - dimensions:
      - [Environment, Service, Operation, RemoteService, RemoteOperation, RemoteEnvironment, RemoteResourceIdentifier, RemoteResourceType]
      - [Environment, Service, Operation, RemoteService, RemoteOperation, RemoteEnvironment]
      - [Environment, Service, Operation, RemoteService, RemoteOperation, RemoteResourceIdentifier, RemoteResourceType]
      - [Environment, Service, Operation, RemoteService, RemoteOperation]
      - [Environment, Service, RemoteService, RemoteEnvironment]
      - [Environment, Service, RemoteService]
      - [Environment, Service, RemoteService, RemoteOperation, RemoteEnvironment, RemoteResourceIdentifier, RemoteResourceType]
      - [Environment, Service, RemoteService, RemoteOperation, RemoteEnvironment]
      - [Environment, Service, RemoteService, RemoteOperation, RemoteResourceIdentifier, RemoteResourceType]
      - [Environment, Service, RemoteService, RemoteOperation]
      - [Environment, Service, RemoteService, RemoteResourceIdentifier, RemoteResourceType]
      - [RemoteService, RemoteResourceIdentifier, RemoteResourceType]
      - [RemoteService]
    label_matchers:
      - label_names:
          - aws.span.kind
        regex: '^(CLIENT|PRODUCER|CONSUMER)$'
    metric_name_selectors:
      - Latency
      - Fault
      - Error