## Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
## SPDX-License-Identifier: Apache-2.0

# This is a reusable workflow for running the E2E test for Application Signals.
# It is meant to be called from another workflow.
# Read more about reusable workflows: https://docs.github.com/en/actions/using-workflows/reusing-workflows#overview
name: E2E Testing
on:
  workflow_call:

permissions:
  id-token: write
  contents: read

concurrency:
  group: '${{ github.workflow }} @ ${{ inputs.aws-region }}'
  cancel-in-progress: false

env:
  CW_AGENT_IMAGE_ECR: ${{ secrets.AWS_ECR_PRIVATE_REGISTRY }}/cwagent-integration-test:${{ github.sha }}
  CW_AGENT_RPM_BUCKET: "s3://${{ secrets.S3_INTEGRATION_BUCKET }}/integration-test/binary/${{ github.sha }}/amazon_linux/amd64/latest/amazon-cloudwatch-agent.rpm"

jobs:
  java-eks-e2e-test:
    uses: aws-observability/aws-application-signals-test-framework/.github/workflows/java-eks-e2e-test.yml@consolidate-release
    secrets: inherit
    with:
      aws-region: us-east-1
      test-cluster-name: 'e2e-cw-agent-test'
      caller-workflow-name: 'main-build'
      patch-image-ecr: ${{ env.CW_AGENT_IMAGE_ECR }}

  java-ec2-default-e2e-test:
    uses: aws-observability/aws-application-signals-test-framework/.github/workflows/java-ec2-default-e2e-test.yml@consolidate-release
    secrets: inherit
    with:
      aws-region: us-east-1
      caller-workflow-name: 'main-build'
      cw-agent-rpm: ${{ env.CW_AGENT_RPM_BUCKET }}

  java-ec2-asg-e2e-test:
    uses: aws-observability/aws-application-signals-test-framework/.github/workflows/java-ec2-asg-e2e-test.yml@consolidate-release
    secrets: inherit
    with:
      aws-region: us-east-1
      caller-workflow-name: 'main-build'
      cw-agent-rpm: ${{ env.CW_AGENT_RPM_BUCKET }}

  java-metric-limiter-e2e-test:
    needs: [ java-eks-e2e-test ]
    uses: aws-observability/aws-application-signals-test-framework/.github/workflows/java-eks-e2e-test.yml@consolidate-release
    secrets: inherit
    with:
      aws-region: us-east-1
      test-cluster-name: 'e2e-cw-agent-test'
      caller-workflow-name: 'main-build'
      patch-image-ecr: ${{ env.CW_AGENT_IMAGE_ECR }}

  python-eks-e2e-test:
    needs: [ java-metric-limiter-e2e-test ]
    uses: aws-observability/aws-application-signals-test-framework/.github/workflows/python-eks-e2e-test.yml@consolidate-release
    secrets: inherit
    with:
      aws-region: us-east-1
      test-cluster-name: 'e2e-cw-agent-test'
      caller-workflow-name: 'main-build'
      patch-image-ecr: ${{ env.CW_AGENT_IMAGE_ECR }}

  python-ec2-default-e2e-test:
    uses: aws-observability/aws-application-signals-test-framework/.github/workflows/python-ec2-default-e2e-test.yml@consolidate-release
    secrets: inherit
    with:
      aws-region: us-east-1
      caller-workflow-name: 'main-build'
      cw-agent-rpm: ${{ env.CW_AGENT_RPM_BUCKET }}

  python-ec2-asg-e2e-test:
    uses: aws-observability/aws-application-signals-test-framework/.github/workflows/python-ec2-asg-e2e-test.yml@consolidate-release
    secrets: inherit
    with:
      aws-region: us-east-1
      caller-workflow-name: 'main-build'
      cw-agent-rpm: ${{ env.CW_AGENT_RPM_BUCKET }}